#############################################
GET http://192.168.1.22:4567/exercise/list

#############################################
GET http://192.168.1.22:4567/exercise/list
  ?body_part_id=2
