POST http://192.168.18.41:4567/user/validate
Content-Type: application/x-www-form-urlencoded

user=20180038
&password=123

#############################################
POST http://192.168.18.32:4567/user/reset
Content-Type: application/x-www-form-urlencoded

dni=12345678666
&email=20180038@aloe.ulima.edu.pe

#############################################
GET http://192.168.1.22:4567/level/list